language: node_js   
node_js:
  - "8"
deploy:
  provider: script
  skip_cleanup: true 
  script: node deploy/deploy.collection.js
  on:  
    branch: 'master'   
notifications:
  webhooks: http://54.157.44.69/mocha
  on_success: never # default: always  
  on_failure: always # default: always
  on_start: never   # default: never
  on_cancel: never # default: always
  on_error: never # default: always
